# Site settings
title: Bastiaan's Profile
email: hendriksbas@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/project-gh-pages-24"
url: "http://bastiaanhendriks.github.io"
twitter_username: bphendriks
github_username:  bastiaanhendriks
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
